<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>07e5fe18-eff7-4f3f-bde9-23e67aab236f</UserSecretsId>
  </PropertyGroup>
<ItemGroup>
	    <PackageReference Include="Syncfusion.Blazor.Cards" Version="31.1.21" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" Version="31.1.21" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="31.1.21" />
</ItemGroup>

  

</Project>
